N-api (node-addon-api)  (#161)
* N-API port initial implementation (WIP)

* clang-format

* default init `name_`

* default construct `name_` in initialiser list to address :

```
../src/object_async/hello_async.cpp:137:1: error: 'object_async::HelloObjectAsync::name_' should be initialized in the member initialization list [-Werror=effc++]
 HelloObjectAsync::HelloObjectAsync(Napi::CallbackInfo const& info)
```

changes. Lines starting

* clang-format

* mode clang-format

* remove extra init (tidy)

* make ctor explicit

* pass Function by const-ref

* annotate with NOLINT + fix passing Function by const-ref in standalone async.

* clang-format

* default 'in-class' init member variable `name_` to placate g++

* remove LTO flags on linux builds

* Revert "remove LTO flags on linux builds" - doh!

This reverts commit 4df69fc6b12ac3ea5da4164777f43b55a6d3b351.

* fix .clang-format

* reimplement CPU intensive task and factor out into separate header
+ formatting + use `override final`

* more cleaning up

* remove redundant `override` c++11

* fix comment

* Make simpler

* Update npm packages

* add link to docs

* Remove Nan references + update link

* remove node-6 builds

* Allocate new Buffer and copy data into it.

* Add empty dtor to avoid memory leaks + make AsyncHelloWorker non-copyable

* clang-format

* clang-tidy

* require  mode-addon-api >= 2.0.0

* Take ownership of underlying data (NOTE: clang-tidy doesn't like this:)

* Add missing return statements

* Use latest (HEAD) hode-addon-api module (fixes SIGILL crash in "Control Flow Integriry" builds (-fsanitize=cfi) with v2.0.0)

* Fix test - use exact error message match

* sleep for 100ms to speed up tests running time

* Store name_ member variable by value + clang tidy

* clang-format

* Initialize result_

* c++ style

* Return std::unique_ptr<std::vector<char>> and stop abusing std::string::data with const_cast (clang-tidy)

* update to use std::vector<char>  + add gsl::owner<T> implementation + explicitely transfer ownership to keep clang-tidy happy (cppcoreguidelines-owning-memory)

* Only target node v10 and v12

* tidy .travis.yml

* Revert "tidy .travis.yml"

This reverts commit eaa4fbfc8388e14766cd3f0c28413b384e34c040.

* Revert "Only target node v10 and v12"

This reverts commit bd6bdb6ca1d7d3b68efc367f22e7fd00dcb4a3c8.

* Fix (hopefully) .travis.yml syntax

* Update node versions

* Add AsyncHelloWorker_v2 implementation which uses `GetResult` method and default `OnOk()` and `OnError`.

* add node v13 targets

* clang-format

* Don't rely on order of args evaluation which is implemetation defined (e.g clang++ differs from GCC) + check `result_` before deref etc.

C++ standard 5.2.2.8 :
"The order of evaluation of arguments is unspecified. All side effects of argument expression evaluations take effect before the function is entered. The order of evaluation of the postfix expression and the argument expression list is unspecified."

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1905.pdf

* Makefile - better target name

* Update link [skip ci]

* attempt to fix coverage problem

* suppress OS X specific leak

* remove references to nan in readme

* avoid re-running npm install when no needed

* use correct mason-js module

* update deps

Co-authored-by: Dane Springmeyer <dane@mapbox.com>